version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: bookexchange-db
    environment:
      POSTGRES_DB: bookexchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookexchange-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: bookexchange-auth
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=bookexchange port=5432 sslmode=disable TimeZone=UTC"
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - bookexchange-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookexchange-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookexchange
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AUTH_SERVICE_URL: http://auth-service:8081
    ports:
      - "8080:8080"
    depends_on:
      - db
      - auth-service
    networks:
      - bookexchange-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookexchange-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - auth-service
    networks:
      - bookexchange-network

volumes:
  postgres_data:

networks:
  bookexchange-network:
    driver: bridge
